set BUSES;
set LINKS within (BUSES cross BUSES);
set PERIODS;

param cost_stability, >= 0;
param cost_lasso_p, >= 0;
param cost_lasso_q, >= 0;

param R {LINKS} ;
param X {LINKS} ;

# param v_nom {BUSES};
# param p_nc_nom {BUSES};
# param q_nc_nom {BUSES};

param dv_lb {BUSES};
param dv_ub {BUSES};

param gp_lb {BUSES};
param gq_lb {BUSES};

param dp_nc {BUSES, PERIODS};
param dq_nc {BUSES, PERIODS};

var epi, >= 0;
var eps, >= 0;

var dv_pos {BUSES, PERIODS}, >=0;
var dv_neg {BUSES, PERIODS}, >=0;

# McCormick auxiliary variables
var k_p_pos{BUSES, PERIODS}, >= 0;
var k_p_neg{BUSES, PERIODS}, >= 0;
var k_q_pos{BUSES, PERIODS}, >= 0;
var k_q_neg{BUSES, PERIODS}, >= 0;

var gp{BUSES}, <= 0;
var gq{BUSES}, <= 0;

minimize FOBJ:
    epi - cost_stability * eps - cost_lasso * sum {i in BUSES} (gp[i] + gq[i])
;
# Epigraph formulation of infinite norm
s.t. INFINITE_NORM_UB: epi >= dv_pos[i, t];
s.t. INFINITE_NORM_LB: epi >= dv_neg[i, t];

# Voltage bounds
s.t. VOLTAGE_LB {i in BUSES, t in PERIODS}: dv_lb[i] <=  - dv_neg[i, t];
s.t. VOLTAGE_UB {i in BUSES, t in PERIODS}: dv_ub[i] >= dv_pos[i, t];

# Ctrl coefficients bounds
s.t. GP_LB {i in BUSES}: - gp[i] >= gp_lb[i];
s.t. GP_UB {i in BUSES}: - gp[i] >= gp_lb[i];


# Linear power flow model
s.t. PFLOW {i in BUSES, t in PERIODS}:
    dv_pos[i, t] - dv_neg[i, t]
    ==
    sum{j in BUSES} (
        # Controlled part
        + R[i, j] * (k_p_pos[i, t] - k_p_neg[i, t])
        + X[i, j] * (k_q_pos[i, t] - k_q_neg[i, t])
        # Uncontrolled part
        + R[i, j] * dp_nc[j, t] + X[i, j] * dq_nc[j, t])
    )
;

# Stability
s.t. STABILITY:
    sum {(i, j) in LINKS} ((R[i, j] * gp[j] + X[i, j] * gq[j])^2) <= 1 - eps
;

# McCormick envelopes autogenerated
s.t. MCCORMICK_P_POS0{i in BUSES, j in PERIODS}:
-k_p_pos[i, t] + gp_lb[i]*dv_pos[i, j] + 0*g_p[i, t] <= gp_lb[i]*0
;
s.t. MCCORMICK_P_POS1{i in BUSES, j in PERIODS}:
-k_p_pos[i, t] + 0*dv_pos[i, j] + dv_ub[i]*g_p[i, t] <= 0*dv_ub[i]
;
s.t. MCCORMICK_P_POS2{i in BUSES, j in PERIODS}:
-k_p_pos[i, t] + 0*dv_pos[i, j] + 0*g_p[i, t] >= 0*0
;
s.t. MCCORMICK_P_POS3{i in BUSES, j in PERIODS}:
-k_p_pos[i, t] + gp_lb[i]*dv_pos[i, j] + dv_ub[i]*g_p[i, t] >= gp_lb[i]*dv_ub[i]
;

s.t. MCCORMICK_P_NEG0{i in BUSES, j in PERIODS}:
-k_p_neg[i, t] + gp_lb[i]*dv_neg[i, j] + 0*g_p[i, t] <= gp_lb[i]*0
;
s.t. MCCORMICK_P_NEG1{i in BUSES, j in PERIODS}:
-k_p_neg[i, t] + 0*dv_neg[i, j] + dv_ub[i]*g_p[i, t] <= 0*dv_ub[i]
;
s.t. MCCORMICK_P_NEG2{i in BUSES, j in PERIODS}:
-k_p_neg[i, t] + 0*dv_neg[i, j] + 0*g_p[i, t] >= 0*0
;
s.t. MCCORMICK_P_NEG3{i in BUSES, j in PERIODS}:
-k_p_neg[i, t] + gp_lb[i]*dv_neg[i, j] + dv_ub[i]*g_p[i, t] >= gp_lb[i]*dv_ub[i]
;

s.t. MCCORMICK_Q_POS0{i in BUSES, j in PERIODS}:
-k_q_pos[i, t] + gq_lb[i]*dv_pos[i, j] + 0*g_q[i, t] <= gq_lb[i]*0
;
s.t. MCCORMICK_Q_POS1{i in BUSES, j in PERIODS}:
-k_q_pos[i, t] + 0*dv_pos[i, j] + dv_ub[i]*g_q[i, t] <= 0*dv_ub[i]
;
s.t. MCCORMICK_Q_POS2{i in BUSES, j in PERIODS}:
-k_q_pos[i, t] + 0*dv_pos[i, j] + 0*g_q[i, t] >= 0*0
;
s.t. MCCORMICK_Q_POS3{i in BUSES, j in PERIODS}:
-k_q_pos[i, t] + gq_lb[i]*dv_pos[i, j] + dv_ub[i]*g_q[i, t] >= gq_lb[i]*dv_ub[i]
;

s.t. MCCORMICK_Q_NEG0{i in BUSES, j in PERIODS}:
-k_q_neg[i, t] + gq_lb[i]*dv_neg[i, j] + 0*g_q[i, t] <= gq_lb[i]*0
;
s.t. MCCORMICK_Q_NEG1{i in BUSES, j in PERIODS}:
-k_q_neg[i, t] + 0*dv_neg[i, j] + dv_ub[i]*g_q[i, t] <= 0*dv_ub[i]
;
s.t. MCCORMICK_Q_NEG2{i in BUSES, j in PERIODS}:
-k_q_neg[i, t] + 0*dv_neg[i, j] + 0*g_q[i, t] >= 0*0
;
s.t. MCCORMICK_Q_NEG3{i in BUSES, j in PERIODS}:
-k_q_neg[i, t] + gq_lb[i]*dv_neg[i, j] + dv_ub[i]*g_q[i, t] >= gq_lb[i]*dv_ub[i]
;










